services:
  database : 
    image : "postgres:16.1"
    ports :
      - "6789:5432"
    volumes :
      - crudvol:/var/lib/postgres/data
    environment :
      - POSTGRES_DB=cakes
      - POSTGRES_PASSWORD=disorder
      - POSTGRES_USER=sacred_silence

volumes :
  crudvol: 
